---
title: "Mid-Atl Clean"
author: "Annie Smith"
date: "2025-11-03"
output: html_document
editor_options: 
  chunk_output_type: console
---

## libraries

```{r}
library(PAMscapes)
library(ggplot2)
library(tidyverse)
library(lubridate)
library(here)
library(dplyr)
library(car)
library(patchwork)
library(ggpubr)
library(rstatix)
library(PAMmisc)
library(dunn.test)
library(smplot2)
library(tsibble)
library(scales)
library(ggpmisc)
library(paletteer)
library(ggh4x)
library(suntools)
library(zoo)
library(wesanderson)
library(openair)

```

##loading full HMD files per site

```{r}
#all_sites_HMD <- read.csv(here("data/all_sites_HMD.csv"))
#runSoundscapeExplorer(all_sites_HMD)

DB01_HMD <- read.csv(here("data/DB01_HMD.csv"))
DB01_HMD$UTC <- as.POSIXct(DB01_HMD$UTC, format= "%Y-%m-%dT%H:%M:%SZ", tz = "GMT")
DB01_HMD$PLATFORM = "DB01"
DB02_HMD <- read.csv(here("data/DB02_HMD.csv"))
DB02_HMD$UTC <- as.POSIXct(DB02_HMD$UTC, format= "%Y-%m-%dT%H:%M:%SZ", tz = "GMT")
DB02_HMD$PLATFORM = "DB02"
DB03_HMD <- read.csv(here("data/DB03_HMD.csv"))
DB03_HMD$UTC <- as.POSIXct(DB03_HMD$UTC, format= "%Y-%m-%dT%H:%M:%SZ", tz = "GMT")
DB03_HMD$PLATFORM = "DB03"

ES01_HMD <- read.csv(here("data/ES01_HMD.csv"))
ES01_HMD$UTC <- as.POSIXct(ES01_HMD$UTC, format= "%Y-%m-%dT%H:%M:%SZ", tz = "GMT")
ES01_HMD$PLATFORM = "ES01"
ES02_HMD <- read.csv(here("data/ES02_HMD.csv"))
ES02_HMD$UTC <- as.POSIXct(ES02_HMD$UTC, format= "%Y-%m-%dT%H:%M:%SZ", tz = "GMT")
ES02_HMD$PLATFORM = "ES02"
ES03_HMD <- read.csv(here("data/ES03_HMD.csv"))
ES03_HMD$UTC <- as.POSIXct(ES03_HMD$UTC, format= "%Y-%m-%dT%H:%M:%SZ", tz = "GMT")
ES03_HMD$PLATFORM = "ES03"

CB01_HMD <- read.csv(here("data/CB01_HMD.csv"))
CB01_HMD$UTC <- as.POSIXct(CB01_HMD$UTC, format= "%Y-%m-%dT%H:%M:%SZ", tz = "GMT")
CB01_HMD$PLATFORM = "CB01"
CB02_HMD <- read.csv(here("data/dataCB02_HMD.csv"))
CB02_HMD$UTC <- as.POSIXct(CB02_HMD$UTC, format= "%Y-%m-%dT%H:%M:%SZ", tz = "GMT")
CB02_HMD$PLATFORM = "CB02"
CB03_HMD <- read.csv(here("data/dataCB03_HMD.csv"))
CB03_HMD$UTC <- as.POSIXct(CB03_HMD$UTC, format= "%m/%d/%Y %H", tz = "GMT")
CB03_HMD <- CB03_HMD[-c(1)]
CB03_HMD$PLATFORM = "CB03"

all_sites <- DB01_HMD%>%
  full_join(DB02_HMD)%>%
  full_join(DB03_HMD)%>%
  full_join(ES01_HMD)%>%
  full_join(ES02_HMD)%>%
  full_join(ES03_HMD)%>%
  full_join(CB01_HMD)%>%
  full_join(CB02_HMD)%>%
  full_join(CB03_HMD)
all_sites$PLATFORM_order= factor(all_sites$PLATFORM, levels = c("DB01","DB02","DB03","ES01","ES02", "ES03", "CB01", "CB02","CB03"))

```

##loading in OL files per site

```{r}
DB01_OL <- read.csv(here("data/DB01_OL.csv"))
DB01_OL <- DB01_OL[-c(1)]
DB01_OL$UTC_fixed <- paste(DB01_OL$UTC_date, DB01_OL$UTC_hour, sep = " ")
DB01_OL$UTC_fixed <- as.POSIXct(DB01_OL$UTC_fixed, format = "%Y-%m-%d %H:%M:%S")
DB01_OL$PLATFORM = "DB01"

DB02_OL <- read.csv(here("data/DB02_OL.csv"))
DB02_OL <- DB02_OL[-c(1)]
DB02_OL$UTC_fixed <- paste(DB02_OL$UTC_date, DB02_OL$UTC_hour, sep = " ")
DB02_OL$UTC_fixed <- as.POSIXct(DB02_OL$UTC_fixed, format = "%Y-%m-%d %H:%M:%S")
DB02_OL$PLATFORM = "DB02"

DB03_OL <- read.csv(here("data/DB03_OL.csv"))
DB03_OL <- DB03_OL[-c(1)]
DB03_OL$UTC_fixed <- paste(DB03_OL$UTC_date, DB03_OL$UTC_hour, sep = " ")
DB03_OL$UTC_fixed <- as.POSIXct(DB03_OL$UTC_fixed, format = "%Y-%m-%d %H:%M:%S")
DB03_OL$PLATFORM = "DB03"

ES01_OL <- read.csv(here("data/ES01_OL.csv"))
ES01_OL <- ES01_OL[-c(1)]
ES01_OL$UTC_fixed <- paste(ES01_OL$UTC_date, ES01_OL$UTC_hour, sep = " ")
ES01_OL$UTC_fixed <- as.POSIXct(ES01_OL$UTC_fixed, format = "%Y-%m-%d %H:%M:%S")
ES01_OL$PLATFORM = "ES01"

ES02_OL <- read.csv(here("data/ES02_OL.csv"))
ES02_OL <- ES02_OL[-c(1)]
ES02_OL$UTC_fixed <- paste(ES02_OL$UTC_date, ES02_OL$UTC_hour, sep = " ")
ES02_OL$UTC_fixed <- as.POSIXct(ES02_OL$UTC_fixed, format = "%Y-%m-%d %H:%M:%S")
ES02_OL$PLATFORM = "ES02"

ES03_OL <- read.csv(here("data/ES03_OL.csv"))
ES03_OL <- ES03_OL[-c(1)]
ES03_OL$UTC_fixed <- paste(ES03_OL$UTC_date, ES03_OL$UTC_hour, sep = " ")
ES03_OL$UTC_fixed <- as.POSIXct(ES03_OL$UTC_fixed, format = "%Y-%m-%d %H:%M:%S")
ES03_OL$PLATFORM = "ES03"

CB01_OL <- read.csv(here("data/CB01_OL.csv"))
CB01_OL <- CB01_OL[-c(1)]
CB01_OL$UTC_fixed <- paste(CB01_OL$UTC_date, CB01_OL$UTC_hour, sep = " ")
CB01_OL$UTC_fixed <- as.POSIXct(CB01_OL$UTC_fixed, format = "%Y-%m-%d %H:%M:%S")
CB01_OL$PLATFORM = "CB01"

CB02_OL <- read.csv(here("data/CB02_OL.csv"))
CB02_OL <- CB02_OL[-c(1)]
CB02_OL$UTC_fixed <- paste(CB02_OL$UTC_date, CB02_OL$UTC_hour, sep = " ")
CB02_OL$UTC_fixed <- as.POSIXct(CB02_OL$UTC_fixed, format = "%Y-%m-%d %H:%M:%S")
CB02_OL$PLATFORM = "CB02"

CB03_OL <- read.csv(here("data/CB03_OL.csv"))
CB03_OL <- CB03_OL[-c(1)]
CB03_OL$UTC_fixed <- paste(CB03_OL$UTC_date, CB03_OL$UTC_hour, sep = " ")
CB03_OL$UTC_fixed <- as.POSIXct(CB03_OL$UTC_fixed, format = "%Y-%m-%d %H:%M:%S")
CB03_OL$PLATFORM = "CB03"
```

##loading in chorus presence files

```{r}
DB01_chorusPresence <- read.csv(here("data/DB01_chorusPresence.csv"))
DB01_chorusPresence$X500_chorus = case_when(DB01_chorusPresence$X500_chorus == 1 ~ "yes",
                                            DB01_chorusPresence$X500_chorus == 0 ~ "no")
DB01_chorusPresence$X1000_chorus = case_when(DB01_chorusPresence$X1000_chorus == 1 ~ "yes",
                                            DB01_chorusPresence$X1000_chorus == 0 ~ "no")
DB01_chorusPresence$X2000_chorus = case_when(DB01_chorusPresence$X2000_chorus == 1 ~ "yes",
                                            DB01_chorusPresence$X2000_chorus == 0 ~ "no")
ES01_chorusPresence <- read.csv(here("data/ES01_chorusPresence.csv"))
ES01_chorusPresence$X500_chorus = case_when(ES01_chorusPresence$X500_chorus == 1 ~ "yes",
                                            ES01_chorusPresence$X500_chorus == 0 ~ "no")
ES01_chorusPresence$X1000_chorus = case_when(ES01_chorusPresence$X1000_chorus == 1 ~ "yes",
                                            ES01_chorusPresence$X1000_chorus == 0 ~ "no")
ES01_chorusPresence$X2000_chorus = case_when(ES01_chorusPresence$X2000_chorus == 1 ~ "yes",
                                            ES01_chorusPresence$X2000_chorus == 0 ~ "no")
CB01_chorusPresence <- read.csv(here("data/CB01_chorusPresence.csv"))
CB01_chorusPresence$X500_chorus = case_when(CB01_chorusPresence$X500_chorus == 1 ~ "yes",
                                            CB01_chorusPresence$X500_chorus == 0 ~ "no")
CB01_chorusPresence$X1000_chorus = case_when(CB01_chorusPresence$X1000_chorus == 1 ~ "yes",
                                            CB01_chorusPresence$X1000_chorus == 0 ~ "no")
CB01_chorusPresence$X2000_chorus = case_when(CB01_chorusPresence$X2000_chorus == 1 ~ "yes",
                                            CB01_chorusPresence$X2000_chorus == 0 ~ "no")
```

##Inshore sites sunsets

```{r}
#DB01
DB01_location <- matrix(c(-74.82, 38.71), nrow = 1)
DB01_date_Time <- seq(ymd_hms("2022-06-10 00:00:00"), ymd_hms("2024-11-08 16:00:00"), by = "1 hour")

Sunset <- sunriset(crds = DB01_location, dateTime = DB01_date_Time, direction = "sunset", POSIXct.out = TRUE)
sunset_datehour <- Sunset %>%
  mutate(UTC_date = date(time))%>%
  mutate(sunset_UTC_hour = hour(time))

sunset_datehour <- sunset_datehour %>%
  group_by(UTC_date, sunset_UTC_hour)%>%
  summarize(n = n())
sunset_datehour$sunset_UTC_hour <- as.character(sunset_datehour$sunset_UTC_hour)
sunset_datehour$UTC_date <- as.character(sunset_datehour$UTC_date)
sunset_datehour <- sunset_datehour[-c(3)]
sunset_datehour$UTC_fixed <- paste(sunset_datehour$UTC_date, sunset_datehour$sunset_UTC_hour, sep = " ")
sunset_datehour$UTC_fixed = as.POSIXct(sunset_datehour$UTC_fixed, format = "%Y-%m-%d %H")


DB01_sunset <- DB01_OL %>%
  right_join(sunset_datehour, join_by(UTC_fixed))

DB01_500Hz <- ggplot(DB01_sunset, aes(x= UTC_fixed, y= OL_500))+
  geom_line(linewidth = 0.75)+
  scale_x_datetime(date_breaks = "3 months", date_labels= "%b %Y", minor_breaks = NULL)+
  theme_bw()+
  xlab("Date")+
  ylab(expression(paste('Median 500Hz Octave Level SPL (db re 1 \u00b5Pa)')))
DB01_2000Hz <- ggplot(DB01_sunset, aes(x= UTC_fixed, y= OL_2000))+
  geom_line(linewidth = 0.75)+
  scale_x_datetime(date_breaks = "3 months", date_labels= "%b %Y", minor_breaks = NULL)+
  theme_bw()+
  xlab("Date")+
  ylab(expression(paste('Median 2000Hz Octave Level SPL (db re 1 \u00b5Pa)')))

DB01_500Hz/DB01_2000Hz +plot_layout(guides = "collect", axis_titles = "collect")

#ES01
ES01_location <- matrix(c(-75.29, 37.69), nrow = 1)
ES01_date_Time <- seq(ymd_hms("2023-10-13 00:00:00"), ymd_hms("2024-09-29 18:00:00"), by = "1 hour")

ES01Sunset <- sunriset(crds = ES01_location, dateTime = ES01_date_Time, direction = "sunset", POSIXct.out = TRUE)
ES01sunset_datehour <- ES01Sunset %>%
  mutate(UTC_date = date(time))%>%
  mutate(sunset_UTC_hour = hour(time))
ES01sunset_datehour <- ES01sunset_datehour %>%
  group_by(UTC_date, sunset_UTC_hour)%>%
  summarize(n = n())
ES01sunset_datehour$sunset_UTC_hour <- as.character(ES01sunset_datehour$sunset_UTC_hour)
ES01sunset_datehour$UTC_date <- as.character(ES01sunset_datehour$UTC_date)
ES01sunset_datehour <- ES01sunset_datehour[-c(3)]
ES01sunset_datehour$UTC_fixed <- paste(ES01sunset_datehour$UTC_date, ES01sunset_datehour$sunset_UTC_hour, sep = " ")
ES01sunset_datehour$UTC_fixed = as.POSIXct(ES01sunset_datehour$UTC_fixed, format = "%Y-%m-%d %H")

ES01_sunset <- ES01_OL %>%
  right_join(ES01sunset_datehour, join_by(UTC_fixed))

ES01_500Hz <- ggplot(ES01_sunset, aes(x= UTC_fixed, y= OL_500))+
  geom_line(linewidth = 0.75)+
  scale_x_datetime(date_breaks = "3 months", date_labels= "%b %Y", minor_breaks = NULL)+
  theme_bw()+
  xlab("Date")+
  ylab(expression(paste('Median 500Hz Octave Level SPL (db re 1 \u00b5Pa)')))
ES01_2000Hz <- ggplot(ES01_sunset, aes(x= UTC_fixed, y= OL_2000))+
  geom_line(linewidth = 0.75)+
  scale_x_datetime(date_breaks = "3 months", date_labels= "%b %Y", minor_breaks = NULL)+
  theme_bw()+
  xlab("Date")+
  ylab(expression(paste('Median 2000Hz Octave Level SPL (db re 1 \u00b5Pa)')))

ES01_500Hz/ES01_2000Hz +plot_layout(guides = "collect", axis_titles = "collect")


#CB01
CB01_location <- matrix(c(-75.67, 36.98), nrow = 1)
CB01_date_Time <- seq(ymd_hms("2022-06-10 00:00:00"), ymd_hms("2024-11-08 16:00:00"), by = "1 hour")

CB01Sunset <- sunriset(crds = CB01_location, dateTime = CB01_date_Time, direction = "sunset", POSIXct.out = TRUE)
CB01sunset_datehour <- CB01Sunset %>%
  mutate(UTC_date = date(time))%>%
  mutate(sunset_UTC_hour = hour(time))
CB01sunset_datehour <- CB01sunset_datehour %>%
  group_by(UTC_date, sunset_UTC_hour)%>%
  summarize(n = n())
CB01sunset_datehour$sunset_UTC_hour <- as.character(CB01sunset_datehour$sunset_UTC_hour)
CB01sunset_datehour$UTC_date <- as.character(CB01sunset_datehour$UTC_date)
CB01sunset_datehour <- CB01sunset_datehour[-c(3)]
CB01sunset_datehour$UTC_fixed <- paste(CB01sunset_datehour$UTC_date, CB01sunset_datehour$sunset_UTC_hour, sep = " ")
CB01sunset_datehour$UTC_fixed = as.POSIXct(CB01sunset_datehour$UTC_fixed, format = "%Y-%m-%d %H")

CB01_sunset <- CB01_OL %>%
  right_join(CB01sunset_datehour, join_by(UTC_fixed))

CB01_500Hz <- ggplot(CB01_sunset, aes(x= UTC_fixed, y= OL_500))+
  geom_line(linewidth = 0.75)+
  scale_x_datetime(date_breaks = "3 months", date_labels= "%b %Y", minor_breaks = NULL)+
  theme_bw()+
  xlab("Date")+
  ylab(expression(paste('Median 500Hz Octave Level SPL (db re 1 \u00b5Pa)')))
CB01_2000Hz <- ggplot(CB01_sunset, aes(x= UTC_fixed, y= OL_2000))+
  geom_line(linewidth = 0.75)+
  scale_x_datetime(date_breaks = "3 months", date_labels= "%b %Y", minor_breaks = NULL)+
  theme_bw()+
  xlab("Date")+
  ylab(expression(paste('Median 2000Hz Octave Level SPL (db re 1 \u00b5Pa)')))

CB01_500Hz/CB01_2000Hz +plot_layout(guides = "collect", axis_titles = "collect")


#ALL INSHORE

inshore_sunsets <- DB01_sunset %>%
  full_join(ES01_sunset) %>%
  full_join(CB01_sunset)

ggplot(inshore_sunsets, aes(x= UTC_fixed, y= OL_500, color= PLATFORM))+
  geom_line(linewidth = 0.75)+
  scale_x_datetime(date_breaks = "3 months", date_labels= "%b %Y", minor_breaks = NULL)+
  theme_bw()+
  xlab("Date")+
  ylab(expression(paste('Median 500Hz Octave Level SPL (db re 1 \u00b5Pa)')))

ggplot(inshore_sunsets, aes(x= UTC_fixed, y= OL_2000, color= PLATFORM))+
  geom_line(linewidth = 0.75)+
  scale_x_datetime(date_breaks = "3 months", date_labels= "%b %Y", minor_breaks = NULL)+
  theme_bw()+
  xlab("Date")+
  ylab(expression(paste('Median 2000Hz Octave Level SPL (db re 1 \u00b5Pa)')))

```

##Inshore sites sunrises and combining individuals

```{r}
#DB01
DB01_location <- matrix(c(-74.82, 38.71), nrow = 1)
DB01_date_Time <- seq(ymd_hms("2022-06-10 00:00:00"), ymd_hms("2024-11-08 16:00:00"), by = "1 hour")

DB01Sunrise <- sunriset(crds = DB01_location, dateTime = DB01_date_Time, direction = "sunrise", POSIXct.out = TRUE)
DB01sunrise_datehour <- DB01Sunrise %>%
  mutate(UTC_date = date(time))%>%
  mutate(sunrise_UTC_hour = hour(time))

DB01sunrise_datehour <- DB01sunrise_datehour %>%
  group_by(UTC_date, sunrise_UTC_hour)%>%
  summarize(n = n())
DB01sunrise_datehour$sunrise_UTC_hour <- as.character(DB01sunrise_datehour$sunrise_UTC_hour)
DB01sunrise_datehour$UTC_date <- as.character(DB01sunrise_datehour$UTC_date)
DB01sunrise_datehour <- DB01sunrise_datehour[-c(3)]
DB01sunrise_datehour$UTC_fixed <- paste(DB01sunrise_datehour$UTC_date, DB01sunrise_datehour$sunrise_UTC_hour, sep = " ")
DB01sunrise_datehour$UTC_fixed = as.POSIXct(DB01sunrise_datehour$UTC_fixed, format = "%Y-%m-%d %H")


DB01_sunrise <- DB01_OL %>%
  right_join(DB01sunrise_datehour, join_by(UTC_fixed))

DB01_500Hz <- ggplot(DB01_suntimes, aes(x= UTC_fixed, y= OL_500, color= sun_time))+
  geom_line(linewidth = 0.75)+
  scale_x_datetime(date_breaks = "3 months", date_labels= "%b %Y", minor_breaks = NULL)+
  theme_bw()+
  xlab("Date")+
  ylab(expression(paste('Median 500Hz Octave Level SPL (db re 1 \u00b5Pa)')))+
#  geom_smooth(aes(group=1,2))+
  scale_color_manual(values= c("#00308790", "#B7130090"))+
  ggtitle("DB01")+
  theme(legend.title= element_blank())+
  ylim(72, 135)
DB01_2000Hz <- ggplot(DB01_suntimes, aes(x= UTC_fixed, y= OL_2000, color= sun_time))+
  geom_line(linewidth = 0.75)+
  scale_x_datetime(date_breaks = "3 months", date_labels= "%b %Y", minor_breaks = NULL)+
  theme_bw()+
  xlab("Date")+
  ylab(expression(paste('Median 2000Hz Octave Level SPL (db re 1 \u00b5Pa)')))+
#  geom_smooth(aes(group=1,2))+
  scale_color_manual(values= c("#00308790", "#B7130090"))+
  theme(legend.title= element_blank())+
  ggtitle("DB01")+
  ylim(72, 135)
  
DB01_sunset$sun_time = "Sunset"
DB01_sunrise$sun_time = "Sunrise"
DB01_suntimes <- DB01_sunrise %>%
  full_join(DB01_sunset)

ggplot(DB01_suntimes, aes(x= UTC_fixed, y= OL_500, color= sun_time, ))+
  geom_line(linewidth = 0.75)+
  scale_x_datetime(date_breaks = "3 months", date_labels= "%b %Y", minor_breaks = NULL)+
  theme_bw()+
  xlab("Date")+
  ylab(expression(paste('Median 500Hz Octave Level SPL (db re 1 \u00b5Pa)')))+
  scale_color_manual(values= c("#00308790", "#B7130090"))


ggplot(DB01_suntimes, aes(x= UTC_fixed, y= OL_2000, color=sun_time, q=0.01))+
  geom_line()+
  theme_bw()+
  xlab("Date")+
  ylab(expression(paste('Median 2000Hz Octave Level SPL (db re 1 \u00b5Pa)')))+
  scale_color_manual(values= c("#00308790", "#B7130090"))+
  scale_fill_manual(values= c("#00308790", "#B7130090"))

DB01_500Hz/DB01_2000Hz +plot_layout(guides = "collect", axis_titles = "collect")

#ES01
ES01_location <- matrix(c(-75.29, 37.69), nrow = 1)
ES01_date_Time <- seq(ymd_hms("2022-06-10 00:00:00"), ymd_hms("2024-11-08 16:00:00"), by = "1 hour")

ES01Sunrise <- sunriset(crds = ES01_location, dateTime = ES01_date_Time, direction = "sunrise", POSIXct.out = TRUE)
ES01sunrise_datehour <- ES01Sunrise %>%
  mutate(UTC_date = date(time))%>%
  mutate(sunrise_UTC_hour = hour(time))

ES01sunrise_datehour <- ES01sunrise_datehour %>%
  group_by(UTC_date, sunrise_UTC_hour)%>%
  summarize(n = n())
ES01sunrise_datehour$sunrise_UTC_hour <- as.character(ES01sunrise_datehour$sunrise_UTC_hour)
ES01sunrise_datehour$UTC_date <- as.character(ES01sunrise_datehour$UTC_date)
ES01sunrise_datehour <- ES01sunrise_datehour[-c(3)]
ES01sunrise_datehour$UTC_fixed <- paste(ES01sunrise_datehour$UTC_date, ES01sunrise_datehour$sunrise_UTC_hour, sep = " ")
ES01sunrise_datehour$UTC_fixed = as.POSIXct(ES01sunrise_datehour$UTC_fixed, format = "%Y-%m-%d %H")

ES01_sunrise <- ES01_OL %>%
  right_join(ES01sunrise_datehour, join_by(UTC_fixed))

ES01_sunset$sun_time = "Sunset"
ES01_sunrise$sun_time = "Sunrise"
ES01_suntimes <- ES01_sunrise %>%
  full_join(ES01_sunset)

ES01_500Hz <- ggplot(ES01_suntimes, aes(x= UTC_fixed, y= OL_500, color= sun_time))+
  geom_line(linewidth = 0.75)+
  scale_x_datetime(date_breaks = "3 months", date_labels= "%b %Y", minor_breaks = NULL)+
  theme_bw()+
  xlab("Date")+
  ylab(expression(paste('Median 500Hz Octave Level SPL (db re 1 \u00b5Pa)')))+
#  geom_smooth(aes(group=1,2))+
  scale_color_manual(values= c("#00308790", "#B7130090"))+
  ggtitle("ES01")+
  theme(legend.title= element_blank())+
  ylim(72, 135)
ES01_2000Hz <- ggplot(ES01_suntimes, aes(x= UTC_fixed, y= OL_2000, color= sun_time))+
  geom_line(linewidth = 0.75)+
  scale_x_datetime(date_breaks = "3 months", date_labels= "%b %Y", minor_breaks = NULL)+
  theme_bw()+
  xlab("Date")+
  ylab(expression(paste('Median 2000Hz Octave Level SPL (db re 1 \u00b5Pa)')))+
#  geom_smooth(aes(group=1,2))+
  scale_color_manual(values= c("#00308790", "#B7130090"))+
  theme(legend.title= element_blank())+
  ggtitle("ES01")+
  ylim(72, 135)

ES01_500Hz/ES01_2000Hz +plot_layout(guides = "collect", axis_titles = "collect")

#CB01
CB01_location <- matrix(c(-75.67, 36.98), nrow = 1)
CB01_date_Time <- seq(ymd_hms("2022-06-10 00:00:00"), ymd_hms("2024-11-08 16:00:00"), by = "1 hour")

CB01Sunrise <- sunriset(crds = CB01_location, dateTime = CB01_date_Time, direction = "sunrise", POSIXct.out = TRUE)
CB01sunrise_datehour <- CB01Sunrise %>%
  mutate(UTC_date = date(time))%>%
  mutate(sunrise_UTC_hour = hour(time))

CB01sunrise_datehour <- CB01sunrise_datehour %>%
  group_by(UTC_date, sunrise_UTC_hour)%>%
  summarize(n = n())
CB01sunrise_datehour$sunrise_UTC_hour <- as.character(CB01sunrise_datehour$sunrise_UTC_hour)
CB01sunrise_datehour$UTC_date <- as.character(CB01sunrise_datehour$UTC_date)
CB01sunrise_datehour <- CB01sunrise_datehour[-c(3)]
CB01sunrise_datehour$UTC_fixed <- paste(CB01sunrise_datehour$UTC_date, CB01sunrise_datehour$sunrise_UTC_hour, sep = " ")
CB01sunrise_datehour$UTC_fixed = as.POSIXct(CB01sunrise_datehour$UTC_fixed, format = "%Y-%m-%d %H")

CB01_sunrise <- CB01_OL %>%
  right_join(CB01sunrise_datehour, join_by(UTC_fixed))

CB01_sunset$sun_time = "Sunset"
CB01_sunrise$sun_time = "Sunrise"
CB01_suntimes <- CB01_sunrise %>%
  full_join(CB01_sunset)

CB01_500Hz <- ggplot(CB01_suntimes, aes(x= UTC_fixed, y= OL_500, color= sun_time))+
  geom_line(linewidth = 0.75)+
  scale_x_datetime(date_breaks = "3 months", date_labels= "%b %Y", minor_breaks = NULL)+
  theme_bw()+
  xlab("Date")+
  ylab(expression(paste('Median 500Hz Octave Level SPL (db re 1 \u00b5Pa)')))+
#  geom_smooth(aes(group=1,2))+
  scale_color_manual(values= c("#00308790", "#B7130090"))+
  ggtitle("CB01")+
  theme(legend.title= element_blank())+
  ylim(72, 135)
CB01_2000Hz <- ggplot(CB01_suntimes, aes(x= UTC_fixed, y= OL_2000, color= sun_time))+
  geom_line(linewidth = 0.75)+
  scale_x_datetime(date_breaks = "3 months", date_labels= "%b %Y", minor_breaks = NULL)+
  theme_bw()+
  xlab("Date")+
  ylab(expression(paste('Median 2000Hz Octave Level SPL (db re 1 \u00b5Pa)')))+
#  geom_smooth(aes(group=1,2))+
  scale_color_manual(values= c("#00308790", "#B7130090"))+
  theme(legend.title= element_blank())+
  ggtitle("CB01")+
  ylim(72, 135)

CB01_500Hz/CB01_2000Hz +plot_layout(guides = "collect", axis_titles = "collect")
```

##combining

```{r}
DB01_2000Hz/ES01_2000Hz/CB01_2000Hz +plot_layout(guides= "collect", axis_titles= "collect")


CB01_1000Hz <- ggplot(CB01_suntimes, aes(x= UTC_fixed, y= OL_1000, color= sun_time))+
  geom_line(linewidth = 0.75)+
  scale_x_datetime(date_breaks = "2 months", date_labels= "%b %Y", minor_breaks = NULL)+
  theme_bw()+
  xlab("Date")+
  ylab(expression(paste('Median 1000Hz Octave Level SPL (db re 1 \u00b5Pa)')))+
#  geom_smooth(aes(group=1,2))+
  scale_color_manual(values= c("#00308790", "#B7130090"))+
  theme(legend.title= element_blank())+
  ggtitle("CB01")+
  ylim(72, 135)

DB01_1000Hz <- ggplot(DB01_suntimes, aes(x= UTC_fixed, y= OL_1000, color= sun_time))+
  geom_line(linewidth = 0.75)+
  scale_x_datetime(date_breaks = "2 months", date_labels= "%b %Y", minor_breaks = NULL)+
  theme_bw()+
  xlab("Date")+
  ylab(expression(paste('Median 1000Hz Octave Level SPL (db re 1 \u00b5Pa)')))+
#  geom_smooth(aes(group=1,2))+
  scale_color_manual(values= c("#00308790", "#B7130090"))+
  theme(legend.title= element_blank())+
  ggtitle("DB01")+
  ylim(72, 135)

ES01_1000Hz <- ggplot(ES01_suntimes, aes(x= UTC_fixed, y= OL_1000, color= sun_time))+
  geom_line(linewidth = 0.75)+
  scale_x_datetime(date_breaks = "2 months", date_labels= "%b %Y", minor_breaks = NULL)+
  theme_bw()+
  xlab("Date")+
  ylab(expression(paste('Median 1000Hz Octave Level SPL (db re 1 \u00b5Pa)')))+
#  geom_smooth(aes(group=1,2))+
  scale_color_manual(values= c("#00308790", "#B7130090"))+
  theme(legend.title= element_blank())+
  ggtitle("ES01")+
  ylim(72, 135)

DB01_1000Hz/ES01_1000Hz/CB01_1000Hz +plot_layout(guides= "collect", axis_titles= "collect")


```

##open air package

```{r}
#smoothing plot using openair

colnames(CB01_OL)[17] <- "date"
colnames(DB01_OL)[17] <- "date"
colnames(ES01_OL)[17] <- "date"
ES01_OL <- ES01_OL[complete.cases(ES01_OL), ]
CB01_OL <- CB01_OL[complete.cases(CB01_OL), ]
DB01_OL <- DB01_OL[complete.cases(DB01_OL), ]

DB01_plot <- timePlot(DB01_OL, type= "PLATFORM", pollutant= c("OL_500", "OL_1000", "OL_2000"), avg.time= "week", y.relation = "same", smooth= FALSE, date.format = "%b-%Y", ylab = (expression(paste("Octave Band SPL (dB re \u00b5Pa" ^ "2", "/Hz)"))))

ES01_plot <- timePlot(ES01_OL, type= "PLATFORM", pollutant= c("OL_500","OL_1000", "OL_2000"), avg.time= "week", y.relation = "same", smooth= FALSE, date.format = "%b-%Y", ylab = (expression(paste("Octave Band SPL (dB re \u00b5Pa" ^ "2", "/Hz)"))))

CB01_plot <- timePlot(CB01_OL, type= "PLATFORM", pollutant= c("OL_500","OL_1000", "OL_2000"), avg.time= "week", y.relation = "same", smooth= FALSE, date.format = "%b-%Y", ylab = (expression(paste("Octave Band SPL (dB re \u00b5Pa" ^ "2", "/Hz)"))))

DB01_plot / ES01_plot / CB01_plot + plot_layout(axes = "collect", guides= "collect")


ES01_extraTime <- seq(ymd_hms("2022-06-10 00:00:00"), ymd_hms("2023-10-13 20:00:00"), by = "1 hour")
ES01_extraTime <- data.frame(date= ES01_extraTime)
ES01_OL <- ES01_OL %>%
 full_join(ES01_extraTime)



smoothTrend(DB01_OL, pollutant = c("OL_500", "OL_1000", "OL_2000"), statistics= "percentile", percentile = c(95), shade= "transparent", ci= FALSE, ylab = (expression(paste("500 Hz Octave Band SPL (dB re \u00b5Pa" ^ "2", "/Hz)"))), main = "DB01")

calendarPlot(DB01_OL, pollutant= "OL_500", year = "2023", annotate= "value")

DB_dates <- DB02_OL %>%
  group_by(date)%>%
  summarize(total = n())

```

##temp data

```{r}
#DB01
DB01_202207Temp <- read.csv(here("data/Temp_data/NEFSC_DE_202207_DB01_Filtered_ST_Temp_data.csv"))
DB01_202301Temp <- read.csv(here("data/Temp_data/NEFSC_DE_202301_DB01_Filtered_ST_Temp_data.csv"))
DB01_202306Temp <- read.csv(here("data/Temp_data/NEFSC_DE_202306_DB01_Filtered_ST_Temp_data.csv"))
DB01_202311Temp <- read.csv(here("data/Temp_data/NEFSC_DE_202311_DB01_Filtered_ST_Temp_data.csv"))
DB01_202405Temp <- read.csv(here("data/Temp_data/NEFSC_DE_202405_DB01_8015_Filtered_ST_Temp_data.csv"))
DB01_202411Temp <- read.csv(here("data/Temp_data/NEFSC_DE_202411_DB01_6105_Filtered_ST_Temp_data.csv"))
#ES01
ES01_202310Temp <- read.csv(here("data/Temp_data/NEFSC_VA_202310_ES01_Filtered_ST_Temp_data.csv"))
ES01_202404Temp <- read.csv(here("data/Temp_data/NEFSC_VA_202404_ES01_6105_Filtered_ST_Temp_data.csv"))
ES01_202409Temp <- read.csv(here("data/Temp_data/NEFSC_VA_202409_ES01_6104_Filtered_ST_Temp_data.csv"))

#CB01
CB01_202206Temp <- read.csv(here("data/Temp_data/NEFSC_VA_202206_CB01_Filtered_ST_Temp_data.csv"))
CB01_202212Temp <- read.csv(here("data/Temp_data/NEFSC_VA_202212_CB01_Filtered_ST_Temp_data.csv"))
CB01_202306Temp <- read.csv(here("data/Temp_data/NEFSC_VA_202306_CB01_Filtered_ST_Temp_data.csv"))
CB01_202311Temp <- read.csv(here("data/Temp_data/NEFSC_VA_202311_CB01_Filtered_ST_Temp_data.csv"))
CB01_202405Temp <- read.csv(here("data/Temp_data/NEFSC_VA_202405_CB01_8014_Filtered_ST_Temp_data.csv"))
CB01_202411Temp <- read.csv(here("data/Temp_data/NEFSC_VA_202411_CB01_8015_Filtered_ST_Temp_data.csv"))

```
