---
title: "Exploratory_chorusing_Annie"
author: "Annie Smith"
date: "2025-08-08"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## load libraries
```{r}
library(PAMscapes)
library(ggplot2)
library(tidyverse)
library(lubridate)
library(here)
library(dplyr)
library(car)
library(patchwork)
library(ggpubr)
library(rstatix)
library(PAMmisc)
library(dunn.test)
library(smplot2)
library(tsibble)
library(scales)
library(ggpmisc)
library(paletteer)

```

## load data

```{r}
DB01 <- read.csv(here("data/DB01_OL.csv"))
DB01 <- DB01[-c(1)]
DB01$UTC <- as.POSIXct(DB01$UTC, format= "%m/%d/%Y %H", tz = "GMT")

runSoundscapeExplorer(DB01)

```

## Delaware Bay- data loading

```{r}
#DB01
#  DB01_202405_Folder <- (here("//nefscdata/PassiveAcoustics/DETECTOR_OUTPUT/PYTHON_SOUNDSCAPE_PYPAM/Raw/NEFSC_DE/NEFSC_DE_202405_DB01/NC"))
#  DB01_202405_Files <- list.files(DB01_202405_Folder, pattern='nc$', full.names=TRUE)
#  DB01_202405 = loadSoundscapeData(DB01_202405_Files, octave = "ol", timeBin= "1hour")

#  

#  DB01_202207 <- read.csv(here("data/DB01_202207_OL.csv"))
#  DB01_202207 <- DB01_202207[-c(1)]
#  DB01_202207$UTC <- as.POSIXct(DB01_202207$UTC, format= "%m/%d/%Y %H", tz = "GMT")

#  DB01 <- DB01_202207 %>%
  full_join(DB01_202301)%>%
  full_join(DB01_202306)%>%
  full_join(DB01_202311)%>%
  full_join(DB01_202405)

#  write.csv(DB01, here("data", "DB01_OL.csv"))
#  write.csv(DB01_202207, here("data", "DB01_202207_OL.csv"))
#  write.csv(DB01_202301, here("data", "DB01_202301_OL.csv"))
#  write.csv(DB01_202306, here("data", "DB01_202306_OL.csv"))
#  write.csv(DB01_202311, here("data", "DB01_202311_OL.csv"))
#  write.csv(DB01_202405, here("data", "DB01_202405_OL.csv"))


#DB02
  DB02_202301_Folder <- (here("//nefscdata/PassiveAcoustics/DETECTOR_OUTPUT/PYTHON_SOUNDSCAPE_PYPAM/Raw/NEFSC_DE/NEFSC_DE_202301_DB02/NC"))
  DB02_202301_Files <- list.files(DB02_202301_Folder, pattern='nc$', full.names=TRUE)
  DB02_202301 = loadSoundscapeData(DB02_202301_Files, octave = "ol", timeBin= "1hour")

write.csv(DB02_202207, here("data", "DB02_202207_OL.csv"))
write.csv(DB02_202301, here("data", "DB02_202301_OL.csv"))

```


